<a href="https://colab.research.google.com/github/majorquev/DBDC_202103_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Jorge Arévalo Labarca <br>
**E-mail ayudante:** jorge.arevalol@usach.cl


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto). 
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [6]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
l0 <- list(1, c("x","y"))
l0

str(l0)


[[1]]
[1] 1

[[2]]
[1] "x" "y"

List of 2
 $ : num 1
 $ : chr [1:2] "x" "y"


In [ ]:
l1 <- list(num = c(1,1,2,3),
           letra = c("a","b"),
           mat = diag(c(10,11)),
           lista = list(n1 = 2, let = "j") )

l1

In [3]:
# estructura
str(l1)

List of 4
 $ num  : num [1:4] 1 1 2 3
 $ letra: chr [1:2] "a" "b"
 $ mat  : num [1:2, 1:2] 10 0 0 11
 $ lista:List of 2
  ..$ n1 : num 2
  ..$ let: chr "j"


In [ ]:
# Podemos guardar los objetos en slots con nombres


In [7]:
# Podemos combinar listas
l2 <- list(res1 = 100,
           id = c("miguel","jorge") )
l2

$res1
[1] 100

$id
[1] "miguel" "jorge"

In [10]:
# Las combinamos
list_combinada <- c(l1,l2)
list_combinada

$num
[1] 1 1 2 3

$letra
[1] "a" "b"

$mat
     [,1] [,2]
[1,]   10    0
[2,]    0   11

$lista
$lista$n1
[1] 2

$lista$let
[1] "j"


$res1
[1] 100

$id
[1] "miguel" "jorge"

In [11]:
length(list_combinada) # Es una lista de 6 elementos

[1] 6

In [13]:
# Acceso mediante posición
l_segundo_elem <- list_combinada[2]
l_segundo_elem

$letra
[1] "a" "b"

In [15]:
class(l_segundo_elem)
typeof(l_segundo_elem)

[1] "list"

[1] "list"

In [16]:
# NOTA lista[.] retorna un lista con un elemento,
list_combinada[2] # Es una lista (de largo 1) con un elemento (vector de strings de largo 2)




$letra
[1] "a" "b"

In [19]:
# lista[[.]] retorna el elmento de la lista lista[.]
segundo_elem <- list_combinada[[2]]
segundo_elem
class(segundo_elem)
typeof(segundo_elem)

[1] "a" "b"

[1] "character"

[1] "character"

In [22]:
#Por eje: Queremos obtener el primer elmento del vector alojado en la segunda entrada de la lista
segundo_elem[1]
list_combinada[[2]][1]

[1] "a"

[1] "a"

In [26]:
# Acceso mediante nombre
list_combinada["letra"] # lista con el objeto



$letra
[1] "a" "b"

In [25]:
list_combinada[["letra"]] # El objeto directamente

[1] "a" "b"

In [27]:
# Si queremos más de una entrada
list_combinada[c("letra", "mat")]

$letra
[1] "a" "b"

$mat
     [,1] [,2]
[1,]   10    0
[2,]    0   11

In [30]:
# acceso vía "$"
list_combinada$letra # Retorna directamente el elemento a consultar, es decir , es lo mismo que
list_combinada[["letra"]]
list_combinada[[2]]




[1] "a" "b"

[1] "a" "b"

[1] "a" "b"

In [33]:
# para saber el largo de la lista/vector
length(list_combinada)
# Para obtener los nombres de la lista
names(list_combinada)
# si quisiéramos renombrar los slots: Ej. queremos cambiar la entrada llamada "id" por "nombre"

names(list_combinada)[6] <- "nombre"


[1] 6

[1] "num"   "letra" "mat"   "lista" "res1"  "id"

In [34]:
list_combinada

$num
[1] 1 1 2 3

$letra
[1] "a" "b"

$mat
     [,1] [,2]
[1,]   10    0
[2,]    0   11

$lista
$lista$n1
[1] 2

$lista$let
[1] "j"


$res1
[1] 100

$nombre
[1] "miguel" "jorge"

In [45]:
# Otro ejemplo de acceso.
# Rescatar la "j"

list_combinada$lista$let

[1] "j"

In [43]:
list_combinada[["lista"]][["let"]]
list_combinada$lista[[2]]

[1] "j"

[1] "j"

In [49]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
## Indicando nombre luedo del "$"" y luego asignando

list_combinada[["nuevo1"]] <- c(5,7)


In [52]:
list_combinada$nuevo2 <- "Una frase completa"

In [53]:
list_combinada

$num
[1] 1 1 2 3

$letra
[1] "a" "b"

$mat
     [,1] [,2]
[1,]   10    0
[2,]    0   11

$lista
$lista$n1
[1] 2

$lista$let
[1] "j"


$res1
[1] 100

$nombre
[1] "miguel" "jorge" 

$nuevo1
[1] 5 7

$nuevo2
[1] "Una frase completa"

In [ ]:
# podemos modificar elementos dentro de un slot



### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí. 

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.
 
 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [62]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)
d1 <- data.frame(id = 1:10,
                 nombre =  paste("nombre",1:10,sep = "_") ,
                 edad = 20:29)
d1

id nombre    edad
1   1 nombre_1  20  
2   2 nombre_2  21  
3   3 nombre_3  22  
4   4 nombre_4  23  
5   5 nombre_5  24  
6   6 nombre_6  25  
7   7 nombre_7  26  
8   8 nombre_8  27  
9   9 nombre_9  28  
10 10 nombre_10 29

In [70]:
str(d1)

'data.frame':	10 obs. of  3 variables:
 $ id    : int  1 2 3 4 5 6 7 8 9 10
 $ nombre: chr  "nombre_1" "nombre_2" "nombre_3" "nombre_4" ...
 $ edad  : int  20 21 22 23 24 25 26 27 28 29


In [65]:
# Acceso a columnas de un data.frame
## Igual que en una lista

d1$edad
#Es lo mismo que :
d1["edad"] # Dataframe con el vector edad
d1[["edad"]] # Vector con las edades

[1] 20 21 22 23 24 25 26 27 28 29

edad
1  20  
2  21  
3  22  
4  23  
5  24  
6  25  
7  26  
8  27  
9  28  
10 29

[1] 20 21 22 23 24 25 26 27 28 29

In [66]:
d1

id nombre    edad
1   1 nombre_1  20  
2   2 nombre_2  21  
3   3 nombre_3  22  
4   4 nombre_4  23  
5   5 nombre_5  24  
6   6 nombre_6  25  
7   7 nombre_7  26  
8   8 nombre_8  27  
9   9 nombre_9  28  
10 10 nombre_10 29

In [69]:
##  Ganamos acceso como matriz
# segundafila de d1
d1[2,]

# segunda fila y tercera columna
d1[2,3]
# lo anterior es lo mismo que
d1[2,"edad"]




id nombre   edad
2 2  nombre_2 21

[1] 21

[1] 21

In [71]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
d1$salario <- rnorm(10,50000,20)


In [72]:
d1

id nombre    edad salario 
1   1 nombre_1  20   49986.25
2   2 nombre_2  21   50000.13
3   3 nombre_3  22   49972.34
4   4 nombre_4  23   50033.72
5   5 nombre_5  24   49999.71
6   6 nombre_6  25   50007.24
7   7 nombre_7  26   50006.86
8   8 nombre_8  27   49988.64
9   9 nombre_9  28   49989.62
10 10 nombre_10 29   49994.52

In [76]:
# Podemos crear columnas a partir de otras 
d1$ratio <- d1$salario/d1$edad  #salario/edad

In [77]:
d1

id nombre    edad salario  id2 ratio   
1   1 nombre_1  20   49986.25 5   2499.313
2   2 nombre_2  21   50000.13 5   2380.959
3   3 nombre_3  22   49972.34 5   2271.470
4   4 nombre_4  23   50033.72 5   2175.379
5   5 nombre_5  24   49999.71 5   2083.321
6   6 nombre_6  25   50007.24 5   2000.290
7   7 nombre_7  26   50006.86 5   1923.341
8   8 nombre_8  27   49988.64 5   1851.431
9   9 nombre_9  28   49989.62 5   1785.343
10 10 nombre_10 29   49994.52 5   1723.949

In [78]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar nombre salario

# Referenciando el nombre de las columnas
d1[c("nombre","salario")]

nombre    salario 
1  nombre_1  49986.25
2  nombre_2  50000.13
3  nombre_3  49972.34
4  nombre_4  50033.72
5  nombre_5  49999.71
6  nombre_6  50007.24
7  nombre_7  50006.86
8  nombre_8  49988.64
9  nombre_9  49989.62
10 nombre_10 49994.52

In [79]:
# Referenciando las posiciones de las columnas (pensado como matriz)
d1[,c(2,4)] # todas las filas, y solo las columnas 2 y 4

nombre    salario 
1  nombre_1  49986.25
2  nombre_2  50000.13
3  nombre_3  49972.34
4  nombre_4  50033.72
5  nombre_5  49999.71
6  nombre_6  50007.24
7  nombre_7  50006.86
8  nombre_8  49988.64
9  nombre_9  49989.62
10 nombre_10 49994.52

In [ ]:
# Se mantiene la lógica de acceso a los sots de una lista.
# Por posición
# Por nombre
# Con "$"

In [81]:
# de la tabla d1, ¿Qué registros tienen un salario mayor 50000?


d1$salario > 50000 

d1[d1$salario > 50000 ,]

[1] FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE

id nombre   edad salario  id2 ratio   
2 2  nombre_2 21   50000.13 5   2380.959
4 4  nombre_4 23   50033.72 5   2175.379
6 6  nombre_6 25   50007.24 5   2000.290
7 7  nombre_7 26   50006.86 5   1923.341

In [84]:
# Si de la consulta anterior, quisiéramos sólo el ratio
d1[d1$salario > 50000 ,"ratio"]
d1[d1$salario > 50000 ,]$ratio
d1$ratio[d1$salario > 50000]


[1] 2380.959 2175.379 2000.290 1923.341

[1] 2380.959 2175.379 2000.290 1923.341

[1] 2380.959 2175.379 2000.290 1923.341

In [ ]:
Consulra

#Consultas 
1. Elminiar columnasen un data.frame
2. Eliminar filas
3. rnorm

In [86]:
# 1.- 
# Primero creamos una columna a borrar
d1$id2 <- 5

In [88]:
d1$id2 <- NULL 

In [89]:
d1

id nombre    edad salario  ratio   
1   1 nombre_1  20   49986.25 2499.313
2   2 nombre_2  21   50000.13 2380.959
3   3 nombre_3  22   49972.34 2271.470
4   4 nombre_4  23   50033.72 2175.379
5   5 nombre_5  24   49999.71 2083.321
6   6 nombre_6  25   50007.24 2000.290
7   7 nombre_7  26   50006.86 1923.341
8   8 nombre_8  27   49988.64 1851.431
9   9 nombre_9  28   49989.62 1785.343
10 10 nombre_10 29   49994.52 1723.949

In [91]:
#2.- Ej: Eliminar todos los registros de d1 que tengan salario menor o igual a 50000
d1 <- d1[d1$salario > 50000 ,]


In [92]:
d1

id nombre   edad salario  ratio   
2 2  nombre_2 21   50000.13 2380.959
4 4  nombre_4 23   50033.72 2175.379
6 6  nombre_6 25   50007.24 2000.290
7 7  nombre_7 26   50006.86 1923.341