<a href="https://colab.research.google.com/github/majorquev/DBDC_202103_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Jorge Arévalo Labarca <br>
**E-mail ayudante:** jorge.arevalol@usach.cl



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una maztriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo. 
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.
 
 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [2]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos

M1 <- matrix(1:6,  nrow = 2, ncol = 3, byrow = FALSE)
M1
M2 <- matrix(1:6,  nrow = 2, ncol = 3, byrow = TRUE)
M2

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [5]:
# clase y atributo dim
class(M1)
typeof(M1)

dim(M1)# Nun de filas  y num de columnas. (2,3)

[1] "matrix" "array"

[1] "integer"

[1] 2 3

In [6]:
# Genere dos vectores del mismo largo y forme una matriz.
v1 <- 1:10
v2 <- 21:30



In [8]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind
cbind(v1,v2) # los vectores se disponen como columnas en la matriz definida.
rbind(v1,v2) # los vectores se disponen como filas en la matriz definida.


v1 v2
 [1,]  1 21
 [2,]  2 22
 [3,]  3 23
 [4,]  4 24
 [5,]  5 25
 [6,]  6 26
 [7,]  7 27
 [8,]  8 28
 [9,]  9 29
[10,] 10 30

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
v1  1    2    3    4    5    6    7    8    9   10   
v2 21   22   23   24   25   26   27   28   29   30

In [10]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)
v3 <- 25:30

cbind(v1,v3)


Warning message in cbind(v1, v3):
“number of rows of result is not a multiple of vector length (arg 2)”


v1 v3
 [1,]  1 25
 [2,]  2 26
 [3,]  3 27
 [4,]  4 28
 [5,]  5 29
 [6,]  6 30
 [7,]  7 25
 [8,]  8 26
 [9,]  9 27
[10,] 10 28

In [11]:
# función diag para la definición de matrices diagonales
#?diag 

diag(c(1,2,5,10))



[,1] [,2] [,3] [,4]
[1,] 1    0    0     0  
[2,] 0    2    0     0  
[3,] 0    0    5     0  
[4,] 0    0    0    10

In [16]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo:
M1
# quiero rescatar el elemento "(2,1)"
M1[2,1]


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[1] 2

In [18]:
# CUIDADO:No es lo mismo que 
M2[c(2,1)] # R entiende también la matriz como un gran vector (por columnas) y lo anterior retorna los elmentos 2 y 1 de dicho vector

[1] 4 1

In [20]:
# Para acceder a una fila completa
M1[2,] # segunda fila


# Para acceder a una columna completa
M1[,3] # tercera columna


[1] 2 4 6

[1] 5 6

In [21]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 5 por un 99 (el 5 de la pos 1,3)
M1[1,3] <- 99
M1

[,1] [,2] [,3]
[1,] 1    3    99  
[2,] 2    4     6

In [ ]:
# Acceso mediante nombres


In [ ]:
M2

In [ ]:
# Acceso mediante nomnbres


In [ ]:
# Acceso mediante "indicatrices" lógicas 
#Quiero obtener los elementos (1,1) y (2,3) de M2
# 1: Crear una matriz de 2x3 con TRUE en dichas posiciones y FALSE en las restantes.



In [ ]:
# Podemos evaluar las casillas de una atriz mediante sentencias lógicas


**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [ ]:
# transponer una matriz


In [ ]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices



In [ ]:
# Multiplicación de matrices
M2 * M1 # multiplicación componente a componente


In [ ]:
# podemos calcular determinantes
# ?det



In [ ]:
# Podemos invertir matrices
# ?solve
